package uiFrame;

import action.LambaiController;
import entity.BaiThi;

public class LambaiFrm extends javax.swing.JFrame {

    /**
     * Creates new form LambaiFrm
     */
    public LambaiFrm(BaiThi baithi) {
        initComponents();
        
        LambaiController controller = new LambaiController(btnNopbai, jtfTenmonhoc, jtfTenbaithi, jtfHocky, jtfManguoidung, jtfTennguoidung);
        controller.setView(baithi);
        		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfTenmonhoc = new javax.swing.JTextField();
        jtfTenbaithi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfHocky = new javax.swing.JTextField();
        jtfTennguoidung = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfManguoidung = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNopbai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaCauhoi1 = new javax.swing.JTextArea();
        jrdCauA1 = new javax.swing.JRadioButton();
        jrdCauC1 = new javax.swing.JRadioButton();
        jrdCauB1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaCauA1 = new javax.swing.JTextArea();
        jrdCauD1 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaCauB1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaCauC1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtaCauD1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtaCauhoi2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtaCauA2 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtaCauB2 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtaCauD2 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtaCauC2 = new javax.swing.JTextArea();
        jrdCauA2 = new javax.swing.JRadioButton();
        jrdCauC2 = new javax.swing.JRadioButton();
        jrdCauB2 = new javax.swing.JRadioButton();
        jrdCauD2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtaCauhoi3 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jtaCauA3 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jtaCauB3 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jtaCauD3 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jtaCauC3 = new javax.swing.JTextArea();
        jrdCauA3 = new javax.swing.JRadioButton();
        jrdCauC3 = new javax.swing.JRadioButton();
        jrdCauB3 = new javax.swing.JRadioButton();
        jrdCauD3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jtaCauhoi4 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jtaCauA4 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jtaCauB4 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jtaCauD4 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jtaCauC4 = new javax.swing.JTextArea();
        jrdCauA4 = new javax.swing.JRadioButton();
        jrdCauC4 = new javax.swing.JRadioButton();
        jrdCauB4 = new javax.swing.JRadioButton();
        jrdCauD4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jtaCauhoi5 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jtaCauA5 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jtaCauB5 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        jtaCauD5 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        jtaCauC5 = new javax.swing.JTextArea();
        jrdCauA5 = new javax.swing.JRadioButton();
        jrdCauC5 = new javax.swing.JRadioButton();
        jrdCauB5 = new javax.swing.JRadioButton();
        jrdCauD5 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jtaCauhoi6 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        jtaCauA6 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        jtaCauB6 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        jtaCauD6 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        jtaCauC6 = new javax.swing.JTextArea();
        jrdCauA6 = new javax.swing.JRadioButton();
        jrdCauC6 = new javax.swing.JRadioButton();
        jrdCauB6 = new javax.swing.JRadioButton();
        jrdCauD6 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        jtaCauhoi7 = new javax.swing.JTextArea();
        jScrollPane33 = new javax.swing.JScrollPane();
        jtaCauA7 = new javax.swing.JTextArea();
        jScrollPane34 = new javax.swing.JScrollPane();
        jtaCauB7 = new javax.swing.JTextArea();
        jScrollPane35 = new javax.swing.JScrollPane();
        jtaCauD7 = new javax.swing.JTextArea();
        jScrollPane36 = new javax.swing.JScrollPane();
        jtaCauC7 = new javax.swing.JTextArea();
        jrdCauA7 = new javax.swing.JRadioButton();
        jrdCauC7 = new javax.swing.JRadioButton();
        jrdCauB7 = new javax.swing.JRadioButton();
        jrdCauD7 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane37 = new javax.swing.JScrollPane();
        jtaCauhoi8 = new javax.swing.JTextArea();
        jScrollPane38 = new javax.swing.JScrollPane();
        jtaCauA8 = new javax.swing.JTextArea();
        jScrollPane39 = new javax.swing.JScrollPane();
        jtaCauB8 = new javax.swing.JTextArea();
        jScrollPane40 = new javax.swing.JScrollPane();
        jtaCauD8 = new javax.swing.JTextArea();
        jScrollPane41 = new javax.swing.JScrollPane();
        jtaCauC8 = new javax.swing.JTextArea();
        jrdCauA8 = new javax.swing.JRadioButton();
        jrdCauC8 = new javax.swing.JRadioButton();
        jrdCauB8 = new javax.swing.JRadioButton();
        jrdCauD8 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane42 = new javax.swing.JScrollPane();
        jtaCauhoi9 = new javax.swing.JTextArea();
        jScrollPane43 = new javax.swing.JScrollPane();
        jtaCauA9 = new javax.swing.JTextArea();
        jScrollPane44 = new javax.swing.JScrollPane();
        jtaCauB9 = new javax.swing.JTextArea();
        jScrollPane45 = new javax.swing.JScrollPane();
        jtaCauD9 = new javax.swing.JTextArea();
        jScrollPane46 = new javax.swing.JScrollPane();
        jtaCauC9 = new javax.swing.JTextArea();
        jrdCauA9 = new javax.swing.JRadioButton();
        jrdCauC9 = new javax.swing.JRadioButton();
        jrdCauB9 = new javax.swing.JRadioButton();
        jrdCauD9 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane47 = new javax.swing.JScrollPane();
        jtaCauhoi10 = new javax.swing.JTextArea();
        jScrollPane48 = new javax.swing.JScrollPane();
        jtaCauA10 = new javax.swing.JTextArea();
        jScrollPane49 = new javax.swing.JScrollPane();
        jtaCauB10 = new javax.swing.JTextArea();
        jScrollPane50 = new javax.swing.JScrollPane();
        jtaCauD10 = new javax.swing.JTextArea();
        jScrollPane51 = new javax.swing.JScrollPane();
        jtaCauC10 = new javax.swing.JTextArea();
        jrdCauA10 = new javax.swing.JRadioButton();
        jrdCauC10 = new javax.swing.JRadioButton();
        jrdCauB10 = new javax.swing.JRadioButton();
        jrdCauD10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Bài thi");

        jtfTenmonhoc.setEditable(false);
        jtfTenmonhoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfTenbaithi.setEditable(false);
        jtfTenbaithi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("HỌC KỲ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tên sinh viên");

        jtfHocky.setEditable(false);
        jtfHocky.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtfHocky.setForeground(new java.awt.Color(204, 0, 0));
        jtfHocky.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jtfTennguoidung.setEditable(false);
        jtfTennguoidung.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mã sinh viên");

        jtfManguoidung.setEditable(false);
        jtfManguoidung.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Môn học");

        btnNopbai.setBackground(new java.awt.Color(204, 0, 0));
        btnNopbai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNopbai.setForeground(new java.awt.Color(255, 255, 255));
        btnNopbai.setText("Nộp Bài");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Câu 1:");

        jtaCauhoi1.setColumns(20);
        jtaCauhoi1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi1.setRows(5);
        jScrollPane2.setViewportView(jtaCauhoi1);

        buttonGroup1.add(jrdCauA1);
        jrdCauA1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA1.setText("");

        buttonGroup1.add(jrdCauC1);
        jrdCauC1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC1.setText("");

        buttonGroup1.add(jrdCauB1);
        jrdCauB1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB1.setText("");

        jtaCauA1.setColumns(20);
        jtaCauA1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA1.setRows(5);
        jScrollPane3.setViewportView(jtaCauA1);

        buttonGroup1.add(jrdCauD1);
        jrdCauD1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD1.setText("");

        jtaCauB1.setColumns(20);
        jtaCauB1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB1.setRows(5);
        jScrollPane4.setViewportView(jtaCauB1);

        jtaCauC1.setColumns(20);
        jtaCauC1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC1.setRows(5);
        jScrollPane5.setViewportView(jtaCauC1);

        jtaCauD1.setColumns(20);
        jtaCauD1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD1.setRows(5);
        jScrollPane6.setViewportView(jtaCauD1);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Câu 2:");

        jtaCauhoi2.setColumns(20);
        jtaCauhoi2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi2.setRows(5);
        jScrollPane7.setViewportView(jtaCauhoi2);

        jtaCauA2.setColumns(20);
        jtaCauA2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA2.setRows(5);
        jScrollPane8.setViewportView(jtaCauA2);

        jtaCauB2.setColumns(20);
        jtaCauB2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB2.setRows(5);
        jScrollPane9.setViewportView(jtaCauB2);

        jtaCauD2.setColumns(20);
        jtaCauD2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD2.setRows(5);
        jScrollPane10.setViewportView(jtaCauD2);

        jtaCauC2.setColumns(20);
        jtaCauC2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC2.setRows(5);
        jScrollPane11.setViewportView(jtaCauC2);

        buttonGroup2.add(jrdCauA2);
        jrdCauA2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA2.setText("");

        buttonGroup2.add(jrdCauC2);
        jrdCauC2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC2.setText("");

        buttonGroup2.add(jrdCauB2);
        jrdCauB2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB2.setText("");

        buttonGroup2.add(jrdCauD2);
        jrdCauD2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD2.setText("");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Câu 3:");

        jtaCauhoi3.setColumns(20);
        jtaCauhoi3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi3.setRows(5);
        jScrollPane12.setViewportView(jtaCauhoi3);

        jtaCauA3.setColumns(20);
        jtaCauA3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA3.setRows(5);
        jScrollPane13.setViewportView(jtaCauA3);

        jtaCauB3.setColumns(20);
        jtaCauB3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB3.setRows(5);
        jScrollPane14.setViewportView(jtaCauB3);

        jtaCauD3.setColumns(20);
        jtaCauD3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD3.setRows(5);
        jScrollPane15.setViewportView(jtaCauD3);

        jtaCauC3.setColumns(20);
        jtaCauC3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC3.setRows(5);
        jScrollPane16.setViewportView(jtaCauC3);

        buttonGroup3.add(jrdCauA3);
        jrdCauA3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA3.setText("");

        buttonGroup3.add(jrdCauC3);
        jrdCauC3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC3.setText("");

        buttonGroup3.add(jrdCauB3);
        jrdCauB3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB3.setText("");

        buttonGroup3.add(jrdCauD3);
        jrdCauD3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD3.setText("");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Câu 4:");

        jtaCauhoi4.setColumns(20);
        jtaCauhoi4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi4.setRows(5);
        jScrollPane17.setViewportView(jtaCauhoi4);

        jtaCauA4.setColumns(20);
        jtaCauA4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA4.setRows(5);
        jScrollPane18.setViewportView(jtaCauA4);

        jtaCauB4.setColumns(20);
        jtaCauB4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB4.setRows(5);
        jScrollPane19.setViewportView(jtaCauB4);

        jtaCauD4.setColumns(20);
        jtaCauD4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD4.setRows(5);
        jScrollPane20.setViewportView(jtaCauD4);

        jtaCauC4.setColumns(20);
        jtaCauC4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC4.setRows(5);
        jScrollPane21.setViewportView(jtaCauC4);

        buttonGroup4.add(jrdCauA4);
        jrdCauA4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA4.setText("");

        buttonGroup4.add(jrdCauC4);
        jrdCauC4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC4.setText("");

        buttonGroup4.add(jrdCauB4);
        jrdCauB4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB4.setText("");

        buttonGroup4.add(jrdCauD4);
        jrdCauD4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD4.setText("");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Câu 5:");

        jtaCauhoi5.setColumns(20);
        jtaCauhoi5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi5.setRows(5);
        jScrollPane22.setViewportView(jtaCauhoi5);

        jtaCauA5.setColumns(20);
        jtaCauA5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA5.setRows(5);
        jScrollPane23.setViewportView(jtaCauA5);

        jtaCauB5.setColumns(20);
        jtaCauB5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB5.setRows(5);
        jScrollPane24.setViewportView(jtaCauB5);

        jtaCauD5.setColumns(20);
        jtaCauD5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD5.setRows(5);
        jScrollPane25.setViewportView(jtaCauD5);

        jtaCauC5.setColumns(20);
        jtaCauC5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC5.setRows(5);
        jScrollPane26.setViewportView(jtaCauC5);

        buttonGroup5.add(jrdCauA5);
        jrdCauA5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA5.setText("");

        buttonGroup5.add(jrdCauC5);
        jrdCauC5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC5.setText("");

        buttonGroup5.add(jrdCauB5);
        jrdCauB5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB5.setText("");

        buttonGroup5.add(jrdCauD5);
        jrdCauD5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD5.setText("");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Câu 6:");

        jtaCauhoi6.setColumns(20);
        jtaCauhoi6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi6.setRows(5);
        jScrollPane27.setViewportView(jtaCauhoi6);

        jtaCauA6.setColumns(20);
        jtaCauA6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA6.setRows(5);
        jScrollPane28.setViewportView(jtaCauA6);

        jtaCauB6.setColumns(20);
        jtaCauB6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB6.setRows(5);
        jScrollPane29.setViewportView(jtaCauB6);

        jtaCauD6.setColumns(20);
        jtaCauD6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD6.setRows(5);
        jScrollPane30.setViewportView(jtaCauD6);

        jtaCauC6.setColumns(20);
        jtaCauC6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC6.setRows(5);
        jScrollPane31.setViewportView(jtaCauC6);

        buttonGroup6.add(jrdCauA6);
        jrdCauA6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA6.setText("");

        buttonGroup6.add(jrdCauC6);
        jrdCauC6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC6.setText("");

        buttonGroup6.add(jrdCauB6);
        jrdCauB6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB6.setText("");

        buttonGroup6.add(jrdCauD6);
        jrdCauD6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD6.setText("");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Câu 7:");

        jtaCauhoi7.setColumns(20);
        jtaCauhoi7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi7.setRows(5);
        jScrollPane32.setViewportView(jtaCauhoi7);

        jtaCauA7.setColumns(20);
        jtaCauA7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA7.setRows(5);
        jScrollPane33.setViewportView(jtaCauA7);

        jtaCauB7.setColumns(20);
        jtaCauB7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB7.setRows(5);
        jScrollPane34.setViewportView(jtaCauB7);

        jtaCauD7.setColumns(20);
        jtaCauD7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD7.setRows(5);
        jScrollPane35.setViewportView(jtaCauD7);

        jtaCauC7.setColumns(20);
        jtaCauC7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC7.setRows(5);
        jScrollPane36.setViewportView(jtaCauC7);

        buttonGroup7.add(jrdCauA7);
        jrdCauA7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA7.setText("");

        buttonGroup7.add(jrdCauC7);
        jrdCauC7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC7.setText("");

        buttonGroup7.add(jrdCauB7);
        jrdCauB7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB7.setText("");

        buttonGroup7.add(jrdCauD7);
        jrdCauD7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD7.setText("");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Câu 8:");

        jtaCauhoi8.setColumns(20);
        jtaCauhoi8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi8.setRows(5);
        jScrollPane37.setViewportView(jtaCauhoi8);

        jtaCauA8.setColumns(20);
        jtaCauA8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA8.setRows(5);
        jScrollPane38.setViewportView(jtaCauA8);

        jtaCauB8.setColumns(20);
        jtaCauB8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB8.setRows(5);
        jScrollPane39.setViewportView(jtaCauB8);

        jtaCauD8.setColumns(20);
        jtaCauD8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD8.setRows(5);
        jScrollPane40.setViewportView(jtaCauD8);

        jtaCauC8.setColumns(20);
        jtaCauC8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC8.setRows(5);
        jScrollPane41.setViewportView(jtaCauC8);

        buttonGroup8.add(jrdCauA8);
        jrdCauA8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA8.setText("");

        buttonGroup8.add(jrdCauC8);
        jrdCauC8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC8.setText("");

        buttonGroup8.add(jrdCauB8);
        jrdCauB8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB8.setText("");

        buttonGroup8.add(jrdCauD8);
        jrdCauD8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD8.setText("");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Câu 9:");

        jtaCauhoi9.setColumns(20);
        jtaCauhoi9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi9.setRows(5);
        jScrollPane42.setViewportView(jtaCauhoi9);

        jtaCauA9.setColumns(20);
        jtaCauA9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA9.setRows(5);
        jScrollPane43.setViewportView(jtaCauA9);

        jtaCauB9.setColumns(20);
        jtaCauB9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB9.setRows(5);
        jScrollPane44.setViewportView(jtaCauB9);

        jtaCauD9.setColumns(20);
        jtaCauD9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD9.setRows(5);
        jScrollPane45.setViewportView(jtaCauD9);

        jtaCauC9.setColumns(20);
        jtaCauC9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC9.setRows(5);
        jScrollPane46.setViewportView(jtaCauC9);

        buttonGroup9.add(jrdCauA9);
        jrdCauA9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA9.setText("");

        buttonGroup9.add(jrdCauC9);
        jrdCauC9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC9.setText("");

        buttonGroup9.add(jrdCauB9);
        jrdCauB9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB9.setText("");

        buttonGroup9.add(jrdCauD9);
        jrdCauD9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD9.setText("");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Câu 10:");

        jtaCauhoi10.setColumns(20);
        jtaCauhoi10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauhoi10.setRows(5);
        jScrollPane47.setViewportView(jtaCauhoi10);

        jtaCauA10.setColumns(20);
        jtaCauA10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauA10.setRows(5);
        jScrollPane48.setViewportView(jtaCauA10);

        jtaCauB10.setColumns(20);
        jtaCauB10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauB10.setRows(5);
        jScrollPane49.setViewportView(jtaCauB10);

        jtaCauD10.setColumns(20);
        jtaCauD10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauD10.setRows(5);
        jScrollPane50.setViewportView(jtaCauD10);

        jtaCauC10.setColumns(20);
        jtaCauC10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaCauC10.setRows(5);
        jScrollPane51.setViewportView(jtaCauC10);

        buttonGroup10.add(jrdCauA10);
        jrdCauA10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauA10.setText("");

        buttonGroup10.add(jrdCauC10);
        jrdCauC10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauC10.setText("");

        buttonGroup10.add(jrdCauB10);
        jrdCauB10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauB10.setText("");

        buttonGroup10.add(jrdCauD10);
        jrdCauD10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrdCauD10.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD1)
                                        .addGap(223, 223, 223))
                                    .addComponent(jrdCauB1)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD2)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB2)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD3)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB3)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD4)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB4)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD5)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB5)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD6)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB6)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD7)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB7)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD8)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB8)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD9)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB9)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauA10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauC10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrdCauD10)
                                        .addGap(219, 219, 219))
                                    .addComponent(jrdCauB10)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD1)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA1)
                            .addComponent(jrdCauB1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD2)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA2)
                            .addComponent(jrdCauB2)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC2))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD3)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA3)
                            .addComponent(jrdCauB3)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC3))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD4)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA4)
                            .addComponent(jrdCauB4)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD5)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA5)
                            .addComponent(jrdCauB5)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD6)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA6)
                            .addComponent(jrdCauB6)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD7)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA7)
                            .addComponent(jrdCauB7)
                            .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD8)
                            .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA8)
                            .addComponent(jrdCauB8)
                            .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD9)
                            .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA9)
                            .addComponent(jrdCauB9)
                            .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauD10)
                            .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdCauA10)
                            .addComponent(jrdCauB10)
                            .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrdCauC10))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfManguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfTennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfTenbaithi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfTenmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfHocky, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(btnNopbai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfHocky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfManguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTenmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTenbaithi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNopbai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnNopbai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrdCauA1;
    private javax.swing.JRadioButton jrdCauA10;
    private javax.swing.JRadioButton jrdCauA2;
    private javax.swing.JRadioButton jrdCauA3;
    private javax.swing.JRadioButton jrdCauA4;
    private javax.swing.JRadioButton jrdCauA5;
    private javax.swing.JRadioButton jrdCauA6;
    private javax.swing.JRadioButton jrdCauA7;
    private javax.swing.JRadioButton jrdCauA8;
    private javax.swing.JRadioButton jrdCauA9;
    private javax.swing.JRadioButton jrdCauB1;
    private javax.swing.JRadioButton jrdCauB10;
    private javax.swing.JRadioButton jrdCauB2;
    private javax.swing.JRadioButton jrdCauB3;
    private javax.swing.JRadioButton jrdCauB4;
    private javax.swing.JRadioButton jrdCauB5;
    private javax.swing.JRadioButton jrdCauB6;
    private javax.swing.JRadioButton jrdCauB7;
    private javax.swing.JRadioButton jrdCauB8;
    private javax.swing.JRadioButton jrdCauB9;
    private javax.swing.JRadioButton jrdCauC1;
    private javax.swing.JRadioButton jrdCauC10;
    private javax.swing.JRadioButton jrdCauC2;
    private javax.swing.JRadioButton jrdCauC3;
    private javax.swing.JRadioButton jrdCauC4;
    private javax.swing.JRadioButton jrdCauC5;
    private javax.swing.JRadioButton jrdCauC6;
    private javax.swing.JRadioButton jrdCauC7;
    private javax.swing.JRadioButton jrdCauC8;
    private javax.swing.JRadioButton jrdCauC9;
    private javax.swing.JRadioButton jrdCauD1;
    private javax.swing.JRadioButton jrdCauD10;
    private javax.swing.JRadioButton jrdCauD2;
    private javax.swing.JRadioButton jrdCauD3;
    private javax.swing.JRadioButton jrdCauD4;
    private javax.swing.JRadioButton jrdCauD5;
    private javax.swing.JRadioButton jrdCauD6;
    private javax.swing.JRadioButton jrdCauD7;
    private javax.swing.JRadioButton jrdCauD8;
    private javax.swing.JRadioButton jrdCauD9;
    private javax.swing.JTextArea jtaCauA1;
    private javax.swing.JTextArea jtaCauA10;
    private javax.swing.JTextArea jtaCauA2;
    private javax.swing.JTextArea jtaCauA3;
    private javax.swing.JTextArea jtaCauA4;
    private javax.swing.JTextArea jtaCauA5;
    private javax.swing.JTextArea jtaCauA6;
    private javax.swing.JTextArea jtaCauA7;
    private javax.swing.JTextArea jtaCauA8;
    private javax.swing.JTextArea jtaCauA9;
    private javax.swing.JTextArea jtaCauB1;
    private javax.swing.JTextArea jtaCauB10;
    private javax.swing.JTextArea jtaCauB2;
    private javax.swing.JTextArea jtaCauB3;
    private javax.swing.JTextArea jtaCauB4;
    private javax.swing.JTextArea jtaCauB5;
    private javax.swing.JTextArea jtaCauB6;
    private javax.swing.JTextArea jtaCauB7;
    private javax.swing.JTextArea jtaCauB8;
    private javax.swing.JTextArea jtaCauB9;
    private javax.swing.JTextArea jtaCauC1;
    private javax.swing.JTextArea jtaCauC10;
    private javax.swing.JTextArea jtaCauC2;
    private javax.swing.JTextArea jtaCauC3;
    private javax.swing.JTextArea jtaCauC4;
    private javax.swing.JTextArea jtaCauC5;
    private javax.swing.JTextArea jtaCauC6;
    private javax.swing.JTextArea jtaCauC7;
    private javax.swing.JTextArea jtaCauC8;
    private javax.swing.JTextArea jtaCauC9;
    private javax.swing.JTextArea jtaCauD1;
    private javax.swing.JTextArea jtaCauD10;
    private javax.swing.JTextArea jtaCauD2;
    private javax.swing.JTextArea jtaCauD3;
    private javax.swing.JTextArea jtaCauD4;
    private javax.swing.JTextArea jtaCauD5;
    private javax.swing.JTextArea jtaCauD6;
    private javax.swing.JTextArea jtaCauD7;
    private javax.swing.JTextArea jtaCauD8;
    private javax.swing.JTextArea jtaCauD9;
    private javax.swing.JTextArea jtaCauhoi1;
    private javax.swing.JTextArea jtaCauhoi10;
    private javax.swing.JTextArea jtaCauhoi2;
    private javax.swing.JTextArea jtaCauhoi3;
    private javax.swing.JTextArea jtaCauhoi4;
    private javax.swing.JTextArea jtaCauhoi5;
    private javax.swing.JTextArea jtaCauhoi6;
    private javax.swing.JTextArea jtaCauhoi7;
    private javax.swing.JTextArea jtaCauhoi8;
    private javax.swing.JTextArea jtaCauhoi9;
    private javax.swing.JTextField jtfHocky;
    private javax.swing.JTextField jtfManguoidung;
    private javax.swing.JTextField jtfTenbaithi;
    private javax.swing.JTextField jtfTenmonhoc;
    private javax.swing.JTextField jtfTennguoidung;
    // End of variables declaration                   
}
