package uiFrame;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import action.ChuyenManHinh;
import bean.DanhMucBean;
import entity.NguoiDung;

public class MainFrmChoGiaoVien extends javax.swing.JFrame {

    /**
     * Creates new form MainFrmChoGiaoVien
     */
    public MainFrmChoGiaoVien(NguoiDung nguoidung) {
        initComponents();
        setTitle("Ứng Dụng Kiểm Tra");
        jlbName.setText(nguoidung.getTenNguoidung());
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("QLBaithiGV", jpnQLBaithiGV, jlbQLBaithiGV));
        listItem.add(new DanhMucBean("QLCauhoi", jpnQLCauhoi, jlbQLCauhoi));
        listItem.add(new DanhMucBean("QLCanhan", jpnQLCanhan, jlbQLCanhan, nguoidung));
        System.out.println(listItem);
        
        ChuyenManHinh controller = new ChuyenManHinh(jpnViewGV);
        controller.setView(jpnQLBaithiGV, jlbQLBaithiGV);
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jpnRootGV = new javax.swing.JPanel();
        jpnMenuGV = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlbName = new javax.swing.JLabel();
        jpnQLBaithiGV = new javax.swing.JPanel();
        jlbQLBaithiGV = new javax.swing.JLabel();
        jpnQLCauhoi = new javax.swing.JPanel();
        jlbQLCauhoi = new javax.swing.JLabel();
        jpnQLCanhan = new javax.swing.JPanel();
        jlbQLCanhan = new javax.swing.JLabel();
        jpnDangxuat = new javax.swing.JPanel();
        jlbDangxuat = new javax.swing.JLabel();
        jpnThoat = new javax.swing.JPanel();
        jlbThoat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpnViewGV = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenuGV.setBackground(new java.awt.Color(82, 83, 81));

        jPanel4.setBackground(new java.awt.Color(232, 64, 60));

        jlbName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbName.setForeground(new java.awt.Color(255, 255, 255));
        jlbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbName.setText("GIÁO VIÊN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jpnQLBaithiGV.setBackground(new java.awt.Color(0, 153, 51));

        jlbQLBaithiGV.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbQLBaithiGV.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLBaithiGV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbQLBaithiGV.setText("QUẢN LÝ BÀI THI");

        javax.swing.GroupLayout jpnQLBaithiGVLayout = new javax.swing.GroupLayout(jpnQLBaithiGV);
        jpnQLBaithiGV.setLayout(jpnQLBaithiGVLayout);
        jpnQLBaithiGVLayout.setHorizontalGroup(
            jpnQLBaithiGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLBaithiGVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLBaithiGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnQLBaithiGVLayout.setVerticalGroup(
            jpnQLBaithiGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLBaithiGVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLBaithiGV, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnQLCauhoi.setBackground(new java.awt.Color(0, 153, 51));

        jlbQLCauhoi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbQLCauhoi.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLCauhoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbQLCauhoi.setText("QUẢN LÝ CÂU HỎI");

        javax.swing.GroupLayout jpnQLCauhoiLayout = new javax.swing.GroupLayout(jpnQLCauhoi);
        jpnQLCauhoi.setLayout(jpnQLCauhoiLayout);
        jpnQLCauhoiLayout.setHorizontalGroup(
            jpnQLCauhoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLCauhoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLCauhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnQLCauhoiLayout.setVerticalGroup(
            jpnQLCauhoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLCauhoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLCauhoi, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnQLCanhan.setBackground(new java.awt.Color(0, 153, 51));

        jlbQLCanhan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbQLCanhan.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLCanhan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbQLCanhan.setText("QUẢN LÝ CÁ NHÂN");

        javax.swing.GroupLayout jpnQLCanhanLayout = new javax.swing.GroupLayout(jpnQLCanhan);
        jpnQLCanhan.setLayout(jpnQLCanhanLayout);
        jpnQLCanhanLayout.setHorizontalGroup(
            jpnQLCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLCanhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLCanhan, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnQLCanhanLayout.setVerticalGroup(
            jpnQLCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLCanhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLCanhan, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnDangxuat.setBackground(new java.awt.Color(0, 153, 51));

        jlbDangxuat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbDangxuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbDangxuat.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout jpnDangxuatLayout = new javax.swing.GroupLayout(jpnDangxuat);
        jpnDangxuat.setLayout(jpnDangxuatLayout);
        jpnDangxuatLayout.setHorizontalGroup(
            jpnDangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDangxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnDangxuatLayout.setVerticalGroup(
            jpnDangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDangxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnThoat.setBackground(new java.awt.Color(0, 153, 51));

        jlbThoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbThoat.setForeground(new java.awt.Color(255, 255, 255));
        jlbThoat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbThoat.setText("THOÁT");

        javax.swing.GroupLayout jpnThoatLayout = new javax.swing.GroupLayout(jpnThoat);
        jpnThoat.setLayout(jpnThoatLayout);
        jpnThoatLayout.setHorizontalGroup(
            jpnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThoatLayout.setVerticalGroup(
            jpnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lập trình phân tán Java - Nhóm 2");

        javax.swing.GroupLayout jpnMenuGVLayout = new javax.swing.GroupLayout(jpnMenuGV);
        jpnMenuGV.setLayout(jpnMenuGVLayout);
        jpnMenuGVLayout.setHorizontalGroup(
            jpnMenuGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQLBaithiGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQLCauhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQLCanhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuGVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnMenuGVLayout.setVerticalGroup(
            jpnMenuGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuGVLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQLBaithiGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnQLCauhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQLCanhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnViewGVLayout = new javax.swing.GroupLayout(jpnViewGV);
        jpnViewGV.setLayout(jpnViewGVLayout);
        jpnViewGVLayout.setHorizontalGroup(
            jpnViewGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        jpnViewGVLayout.setVerticalGroup(
            jpnViewGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootGVLayout = new javax.swing.GroupLayout(jpnRootGV);
        jpnRootGV.setLayout(jpnRootGVLayout);
        jpnRootGVLayout.setHorizontalGroup(
            jpnRootGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootGVLayout.createSequentialGroup()
                .addComponent(jpnMenuGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnViewGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootGVLayout.setVerticalGroup(
            jpnRootGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenuGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnViewGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRootGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRootGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrmChoGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrmChoGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrmChoGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrmChoGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrmChoGiaoVien(new NguoiDung()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbDangxuat;
    private javax.swing.JLabel jlbQLBaithiGV;
    private javax.swing.JLabel jlbQLCanhan;
    private javax.swing.JLabel jlbQLCauhoi;
    private javax.swing.JLabel jlbThoat;
    private javax.swing.JPanel jpnDangxuat;
    private javax.swing.JPanel jpnMenuGV;
    private javax.swing.JPanel jpnQLBaithiGV;
    private javax.swing.JPanel jpnQLCanhan;
    private javax.swing.JPanel jpnQLCauhoi;
    private javax.swing.JPanel jpnRootGV;
    private javax.swing.JPanel jpnThoat;
    private javax.swing.JPanel jpnViewGV;
    // End of variables declaration                   
}

